//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazzCrypt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazzCrypt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifndef DECRYPT_H
        ///#define DECRYPT_H
        ///
        ///#include &lt;stdlib.h&gt;
        ///#include &lt;stdarg.h&gt;
        ///
        ///const char XORKEY = &apos;%ENC_KEY%&apos;;
        ///char* Decrypt(int count, ...);
        ///
        ///#endif.
        /// </summary>
        internal static string DecryptHeader {
            get {
                return ResourceManager.GetString("DecryptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;Decrypt.h&quot;
        ///
        ///[junk_enable]
        ///
        ///char* Decrypt(int count, ...) {
        ///    va_list ap;
        ///    char* buffer = new char[count + 1];
        ///    va_start(ap, count);
        ///    for (int i = 0; i &lt; count; i++) {
        ///        char read = va_arg(ap, char);
        ///        buffer[i] = (read ^ ((XORKEY + i) % 0xFF));
        ///    }
        ///    va_end(ap);
        ///    buffer[count] = &apos;\0&apos;;
        ///    return buffer;
        ///}.
        /// </summary>
        internal static string DecryptSource {
            get {
                return ResourceManager.GetString("DecryptSource", resourceCulture);
            }
        }
    }
}
